package com.millionnaire.engine.core.event;

/** 命令拒绝原因。拒绝不改变业务状态（只消耗序号、推进接收水位）、不消耗随机数。 */
public enum RejectionCode {
    TIME_REGRESSION,
    UNSUPPORTED_COMMAND,
    INVALID_ARGUMENT,
    ROOM_CLOSED,
    ALREADY_MEMBER,
    NOT_MEMBER,
    ROOM_FULL,
    INVALID_NICKNAME,
    NOT_HOST,
    CANNOT_KICK_SELF,
    INVALID_SETTINGS,
    CAPACITY_EXCEEDED,
    UNCHANGED,
    GAME_IN_PROGRESS,
    NOT_IN_GAME,
    NOT_ALL_READY,
    NOT_ENOUGH_PLAYERS,
    NOT_ALLOWED,
    GAME_MISMATCH,
    ALREADY_REQUESTED,
    NOT_YOUR_TURN,
    WRONG_STAGE,
    INSUFFICIENT_CASH,
    CONTROL_NOT_MANUAL,
    STALE_OBSERVATION,
    INVALID_TRANSITION,
    NO_ACTIVE_WINDOW,
    WINDOW_MISMATCH,
    WINDOW_NOT_OPEN,
    WINDOW_PAUSED,
    WINDOW_ALREADY_ACTIVE,
    NOT_PAUSED,
    NOT_YOUR_WINDOW,
    /** 功能属于后续里程碑（如土地拍卖 M5）。 */
    NOT_AVAILABLE,
    INVALID_TILE,
    NOT_OWNER,
    ALREADY_OWNED,
    MORTGAGED,
    NOT_MORTGAGED,
    MAX_LEVEL,
    NOT_AT_BANK,
    ASSET_LOCKED,
    NOT_ALIVE,
    DRAINING,
    /** 手里没有这张卡。 */
    NO_CARD,
    /** 本轮主动用卡机会已用掉。 */
    CARD_USED,
    /** 当前位置 / 目标不满足这张卡的使用条件（卡不消耗）。 */
    NO_TARGET
}
